### ISSUE TITLE
Doesn't work on Firefox

### ISSUE THREAD

**Issue by suy** [Johannes1509/fake-artist-word-generator#2]
Hi! Thanks for the project! I just found it this morning, and it's nice to have.

I would like to know if you can try it on Firefox, as I've realized that neither on mobile or desktop it works. Some of the messages come untranslated as well. I can't check it myself now for more info, but let me know if you need help reproducing the issue.

Cheers.

**Comment by suy** [comment]
Actually... I just tried on Chromium, and it fails as well... This is how it shows, BTW, the strings I imagine are translation placeholders.
![image](https://github.com/user-attachments/assets/6793d743-9f17-450a-bee5-55c32841b9f1)

**Comment by Johannes1509** [comment]
Hey suy, thanks for your issue. I will try it on Firefox and fix the problem :)

**Comment by Johannes1509** [comment]
Hey @suy !
I tried to recreate the error, but the translation/display of the words always worked correctly (in Chrome, Safari, Firefox, Edge). However, since Bootstrap & JQuery was dynamically integrated (was loaded when loading CDNs), I have now stored the files directly locally (this could match the error pattern from https://stackoverflow.com/a/34287036). Can you check if the error still occurs?

Best regards and Merry Christmas!
Johannes

**Comment by suy** [comment]
Thank you for taking the time to look at it!

I still experience the same both on latest Firefox, and an Ungoogled Chromium (that I'm not so sure is 100% up to date).

I've checked the developer console on both, and it seems the reason is that on top of i18n.js the `const lang` variable is assigned again to English. Perhaps it's not happening to you if you have it in German. :)

It's been ages since I did JS, but I suppose just changing the `lang` variable to be declared with `let` instead of `const` would do.

Thank you again, and Merry Christmas.

**Comment by Johannes1509** [comment]
Thanks for your hint. Abosult correct, there should be "let" instead of "const" to set the value for browser languages != "de" to English. 
I was able to reproduce the error in the old version and since the patch from now its working as designes. Can you check one last time to see if it works for you?

**Comment by suy** [comment]
Excellent! Yes, now it works on desktop and on mobile. :-)

Thank you for the early Christmas present. If I manage to localize it to Spanish and/or Catalan, I'll hopefully be able to give it a go with family, and submit a pull request.

**Comment by Johannes1509** [comment]
That sounds great! I'm looking forward to your pull request ;)
